name: Weekly Quantum Computing News Update

on:
  schedule:
    # Runs at 00:00 UTC every Monday
    - cron: '0 0 * * 1'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-news: # Renamed job for clarity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        env:
          BRAVE_API_KEY: ${{ secrets.BRAVE_API_KEY }}
        run: python update_readme.py

      - name: Commit and push if changes exist
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Add README.md and any new/changed files in news_history
          # Also add update_readme.py itself if it were changed, but it's committed by user.
          # news_history might not exist on first run if script fails before creating it.
          # So, ensure the command doesn't fail if news_history doesn't exist.
          git add README.md
          if [ -d "news_history" ]; then
            git add news_history/*.json
          fi
          
          # Check if there are any staged changes before committing
          if ! git diff --staged --quiet; then
            git commit -m "docs: update weekly news and history [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
